version: "3"

services:
  db:
    image: postgres:12
    hostname: library_db
    container_name: library_db
    volumes:
      - postgres_database:/var/lib/postgresql/data
    environment: 
      - POSTGRES_DB=library_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432 
    networks:
      - library_network

  library_backend:
    build: ./library_back
    container_name: library_back
    volumes:
      - ./library_back:/code
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - library_network

  library_frontend:
    build: ./library_front
    container_name: library_front
    volumes:
      - ./library_front:/app
    ports:
      - 3000:3000
    depends_on:
      - library_backend
    networks:
      - library_network

  library_nginx:
    image: nginx:1.22.0-alpine
    container_name: library_nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - library_frontend
    depends_on:
      - library_frontend
    networks:
      - library_network
    

volumes:
  postgres_database:

networks:
  library_network:
    driver: bridge