const styles = {
  primary: {
    backgroundColor: 'black',
    color: 'white',
    fontFamily: 'Montserrat',
    fontSize: '24px',
    fontWeight: 'bold',
    width: '35vh',
    height: '5vh',
    borderRadius: '15px',
    border: '1px solid white',
    boxShadow: '2px 2px lightgray',
    margin: '5px',
    boxSizing: 'border-box',
    outline: '0',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: '2rem',
  },
  secondary: {
    backgroundColor: 'white',
    color: 'black',
    fontFamily: 'Montserrat',
    fontSize: '24px',
    fontWeight: 'bold',
    width: '35vh',
    height: '5vh',
    borderRadius: '15px',
    border: '1px solid black',
    boxShadow: '2px 2px lightgray',
    margin: '5px',
    boxSizing: 'border-box',
    outline: '0',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: '2rem',
  },
  side: {
    backgroundColor: 'black',
    color: 'white',
    fontFamily: 'Montserrat',
    fontSize: '24px',
    fontWeight: 'bold',
    width: '25vh',
    height: '5vh',
    borderRadius: '15px',
    border: '1px solid white',
    boxShadow: '2px 2px lightgray',
    margin: '5px',
    boxSizing: 'border-box',
    outline: '0',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: '2rem',
  },

  bookButton: {
    backgroundColor: 'black',
    color: 'white',
    fontFamily: 'Montserrat',
    fontSize: '15px',
    fontWeight: 'bold',
    width: '15vh',
    height: '5vh',
    borderRadius: '15px',
    border: '1px solid white',
    boxShadow: '2px 2px lightgray',
    margin: '3px',
    boxSizing: 'border-box',
    outline: '0',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  }
};

export default styles;